import fs from 'node:fs'; import path from 'node:path'; import yaml from 'js-yaml';
const root=process.cwd(); const contentRoot=path.join(root,'src/content'); const collections=['projects','publications','people','news','talks']; const errors:string[]=[];
const entries=new Map<string,Map<string,any>>();
for(const collection of collections){const map=new Map<string,any>();const dir=path.join(contentRoot,collection);for(const file of fs.readdirSync(dir).filter(f=>/\.mdx?$/.test(f))){const raw=fs.readFileSync(path.join(dir,file),'utf8');const match=raw.match(/^---\n([\s\S]*?)\n---/);if(!match){errors.push(`${collection}/${file}: missing YAML frontmatter`);continue}try{const data=yaml.load(match[1]) as any;const id=file.replace(/\.mdx?$/,'');if(map.has(id))errors.push(`${collection}: duplicate id ${id}`);map.set(id,data);if(!data.title)errors.push(`${collection}/${file}: title is required`);if(data.start&&data.end&&String(data.end)<String(data.start))errors.push(`${collection}/${file}: end must not precede start`)}catch(e){errors.push(`${collection}/${file}: ${e}`)}}entries.set(collection,map)}
const has=(c:string,id:string)=>entries.get(c)?.has(id); const check=(file:string,field:string,ids:unknown,c:string)=>{if(!Array.isArray(ids))return;for(const id of ids)if(typeof id!=='string'||!has(c,id))errors.push(`${file}: ${field} references missing ${c} entry '${id}'`)};
for(const [id,data] of entries.get('projects')!){const file=`projects/${id}.md`;check(file,'people',data.people,'people');check(file,'publications',data.publications,'publications');check(file,'relatedProjects',data.relatedProjects,'projects')}
for(const [id,data] of entries.get('publications')!){const file=`publications/${id}.md`;check(file,'projects',data.projects,'projects');for(const author of data.authors??[])if(author.person&&!has('people',author.person))errors.push(`${file}: author references missing person '${author.person}'`)}
const research=yaml.load(fs.readFileSync(path.join(root,'src/data/research.yaml'),'utf8')) as any[];const topics=new Set(research.map(t=>t.slug));for(const [collection,map] of entries)for(const [id,data] of map)for(const topic of data.topics??[])if(!topics.has(topic))errors.push(`${collection}/${id}: missing topic '${topic}'`);
if(errors.length){console.error(`Content validation failed:\n- ${errors.join('\n- ')}`);process.exit(1)}console.log(`Content references valid: ${[...entries.values()].reduce((n,m)=>n+m.size,0)} entries, ${topics.size} topics.`);
